---
title: "Untitled"
output: html_document
---

```{r load scatterplot data}
library(rmongodb)
library(ggplot2)
if (file.exists("Dat/SampleCitations100000perYear.rds")) {
    data <- readRDS("Dat/SampleCitations100000perYear.rds")
} else {
    mongo <- mongo.create()
    mongo.is.connected(mongo)
    db <- "sotonproject"
    data <- mongo.find.all(mongo, "sotonproject.SampleCitations100000perYear")
    mongo.destroy(mongo)
    data <- lapply(data, unlist)
    data <- as.data.frame(data)
    data <- t(data)[,2:3]
    rownames(data) <- NULL
    colnames(data) <- c("citedBy", "msDiff")
    data <- as.data.frame(data)
    data$msDiff <- as.numeric(as.character(data$msDiff))
    saveRDS(data, "Dat/SampleCitations100000perYear.rds")
}

```

```{r}
gg <- ggplot(data, aes(x = msDiff)) + geom_histogram() 
gg1 <- gg + scale_x_log10() #+ scale_y_log10()

dat <- dplyr::filter(data, !(citedBy %in% c("cited by applicant", "cited by third party")))
gg2 <- ggplot(dat, aes(x = msDiff, fill = citedBy)) + stat_bin()
gg3 <- gg2 + scale_x_log10() #+ scale_y_log10()
```

```{r}
gg
gg1
gg2
gg3
saveRDS(gg, "Dat/SampleCitations100000plot.rds")

```

1e10 is about a third of a year
1e11 is about 3 years
1e12 is about 30 years
mean is around 10^11.4 which is about 8 years. 